image:
  - Ubuntu

clone_folder: /usr/go/src/github.com/dragosv/matrix

environment:
  GOPATH: /usr/go/

stack: go 1.16

before_test:
  - cover -delete

test_script:
  - go test ./...

after_test:
  - cmd: cover -report codecov