image:
  - Ubuntu

clone_folder: /usr/go/src/github.com/dragosv/matrix

environment:
  GOPATH: /usr/go/

stack: go 1.16

build:
  - run: go mod download
  - run: go mod verify
  - run: go build

test_script:
  - go test ./...

