language: go
dist: focal
addons:
  sonarcloud:
    organization: dragosv
    token:
      secure: Vmt/0XifumY0jCG76rurH3zMenxybjGag0aZ8A1aU4tOI1S9z7lFgANt48tgn8XsQ5cfemMyRgZxV8swJAyd7TEFbVg+QIO2l/IziSCn8waPqoXTQepj5z/+wXrgngJ5XLcaLQm84T480NCF8DzpAWEeJ59v4PEzWUw9e66xH0dVAoG+/SewhjWKlNO/WQUVh7yNrQ8HHL8RIBxb2dFvVS4NmS8cfX71gD1hnk4wHCY/6adyQoyJRo8tLGDKKs20A7ZyfOadqqaURFEVqoC64Kkj3dcnqM8ahrUi6NauamDZS1ebY2O+f69Crl5uJz/DRGpI1x6J7sACuYbbK2ZwVN3HWN12FB3r7PHC/kU9Sk0+cy031CYQ7M/9+h7bCuJaW0lAfYF3F1MAZe177J56/VON7yPMh8nPOmBJYJeC4CGrKjYZYX/ESMDo6zcD4KeF5tJ+k+1daaoXmks7EXEr724oTRcrHUt+w4QkA00r5n9L6E42aunome7ZhEfMYhZ5vD0eWaaxiBx+HYdZCnJ0Qemf1BFj8nFaZKTPnG3pqmcXGL2AB54QeFI2/ubnUTEd4Rl3BFKZ42cPW1daBac7RLJfcGAwjWMrhxC9FKZDrGbe7TH0k02UdXTVxMC11T5Rgi0to3MHIa42SXA+SnTMnPAa0BPD2LJdFzzXBiRxiE0=
env:
  global:
  - CACHE_NAME=${TRAVIS_ARCH}
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - secure: gWRk2ymS0HRZTWIxp74bzRMTYOUaEkplVFz8e+sezuFFD0l2NvO5KMrOi79sodFvFp6FDiqzRE0WYT6eorxVWYHq+juvIA8fSGQG8eRItjRTKiqEsJAzQ5XyHE0Rhf9RTworq/lHBmQjCssZ2+aUNBPvNyi+JjE29/UyrPIhfucPv0SE8sbIEA3kOVR9QJXWaiScPbPjk90AK3wAjyZAjN+iTdUbZajn/6gUYicYJpB9vAcAUOsCgV70blU/LcQ+tOpsrxxoTtpwMmQdQrpESdCZqVYIXkQWvqGAwKcFwZZWGditnQwoEBw49XcAb+cP/jS9+un8KuhqGoISIIAZ2OslR4RxSbqlFdylB7gwRQeIPa1ZySQklQbvIP8gCmFrN3b4wNvaEsXynZ5Ty5dya924DDQ5U6X94GTu8de04mcrNq9z5Ki/FlXJs81KVwCHudPWh6TDQL+7xlewFPIhiXKB3sIdi2z7zBgy38uDD+q8WyN/kjHHVALT8Bawr0XvDzLNhTIdTIQ2kBt3fXmmONOM8Z+4QE7uwAAd56ZSTXzjJ3+egqgFNHXvgvdfuqbqlipx39ctDtI+06fAFjWrxUovjc/AU36Q/IZuySZPsHJ7LzTqx82udZIFk/WtoRVlVlpjoiamxrj6cm0uh96K8aYC2oc/8sc4Ej/r3MRSWTc=
git:
  depth: false
go:
- 1.16.6
- master
arch:
- amd64
#- arm64
os:
- linux
#- osx
#- windows
jobs:
  allow_failures:
  - go: master
  - arch: arm64
  fast_finish: true
  exclude:
  - os: windows
    go: master
  - arch: arm64
    os: osx
  - arch: arm64
    os: windows
cache:
  directories:
  - "$HOME/gopath/pkg/mod"
  - "$HOME/.cache/go-build"
  - "$HOME/Library/Caches/go-build"
  - "$HOME/AppData/Local/go-build"
  - "$HOME/.sonar/cache"
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install mingw -y; export PATH=/c/tools/mingw64/bin:"$PATH";
  fi
install:
- mkdir -p $HOME/src
- mv $TRAVIS_BUILD_DIR $HOME/src
- export TRAVIS_BUILD_DIR=$HOME/src/matrix
- cd $HOME/src/matrix
- go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
script:
- go mod download
- go mod verify
- go build
- go test ./... -coverprofile=coverage.txt -covermode=atomic
- go tool cover -func=coverage.txt
- cp coverage.txt coverage.out
- golangci-lint run > golangci-lint-report.out || true
#- sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)
