package main

import (
	_ "github.com/dragosv/matrix/docs" // docs are generated by Swag CLI, have to import it.
	"github.com/dragosv/matrix/handlers"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
)

// @title Matrix web server API
// @version 1.0
// @description Basic web server written in GoLang that performs operations on a matrix.
// @contact.name Dragos Varovici
// @contact.url https://github.com/dragosv
// @license.name Mozilla Public License 2.0
// @license.url https://www.mozilla.org/en-US/MPL/2.0/
// @host localhost:8080
// @basePath /
func main() {
	router := gin.New()

	handlers.SetupMatrixHandlers(router)

	// use ginSwagger middleware to serve the API docs
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.Run()
}
