on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

name: Sonarcloud Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Go Linter
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - run: go mod download
      - run: go mod verify
      - run: go build
      - run: go test ./... -coverprofile=coverage.out -covermode=atomic
      - run: go tool cover -func=coverage.out
      - run: go vet ./...
      - run: staticcheck ./... > linter.out || true
      - run: staticcheck ./... -f sarif > linter.sarif || true
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: linter.sarif

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
